### ISSUE TITLE
A description is wrong in spam tutorial

### ISSUE THREAD

**Issue by roy29fuku** [snorkel-team/snorkel-tutorials#132]
Hi Snorkel team!

Thank you for your great job!
I am enjoying the tutorial.

I found a bit of a mess‐up in In [11]: of [01_spam_tutorial.ipynb](https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/01_spam_tutorial.ipynb).

I think "coverage_check" and "coverage_check_out" are replaced.
Check out!

Regards,
roy29fuku

**Comment by ajratner** [comment]
@roy29fuku thanks for the catch on this typo!  Submitting a fix PR (also always feel free to directly submit PRs too!)

Thanks,
Alex
