### ISSUE TITLE
Incorrect wording in spam tutorial

### ISSUE THREAD

**Issue by haochuanwei** [snorkel-team/snorkel-tutorials#140]
In this Youtube spam tutorial (https://www.snorkel.org/use-cases/01-spam-tutorial), and in this following sentence:

> We can also run error analysis after the label model has been trained. For example, let’s take a look at 5 random **false positives** from the dev set, which might **inspire some more LFs that vote SPAM**.

I believe that you meant _false negatives_ instead of false positives, especially if you look at the corresponding code:
```python
buckets = get_label_buckets(Y_dev, preds_dev[:, 1])
df_fp_dev = df_dev[["text", "label"]].iloc[buckets[(SPAM, HAM)]]
```

This subset of data is the points where Y_dev says SPAM and prediction says HAM.

**Comment by vincentschen** [comment]
@haochuanwei: Yep, that looks incorrect — thanks for the catch!
