### ISSUE TITLE
PandasLFApplier: ImportError: cannot import name 'DataFrameGroupBy'/'PanelGroupBy'

### ISSUE THREAD

**Issue by egynzhu** [snorkel-team/snorkel-tutorials#145]
## Issue description
In the crowdsourcing tutorial, the following error is given while running PandasLFApplier.

## Code example/repro steps
applier = PandasLFApplier(worker_lfs)
L_train = applier.apply(df_train)
L_dev = applier.apply(df_dev)

## Screenshots
![Screenshot from 2019-08-29 00-55-55](https://user-images.githubusercontent.com/35700260/63911301-c9210400-c9f7-11e9-83c6-e2d04780cccd.png)

## System info
Followed the conda virtual environment steps
pandas==0.24.0
tqdm==4.29.1

**Comment by henryre** [comment]
Hi @egynzhu, thanks for trying out Snorkel! This is a know compatibility issue between certain versions of tdqm and Pandas (https://github.com/tqdm/tqdm/issues/555, https://github.com/tqdm/tqdm/issues/780). However for the versions you listed (and those currently pinned in Snorkel), I'm seeing no issues. Are you using a virtual environment?

**Comment by egynzhu** [comment]
@henryre 
Yes, I followed the steps to create a virtual environment using conda. I switched to Docker today and everything ran smoothly. Thank you!

**Comment by henryre** [comment]
@egynzhu glad you got it working! If you end up trying the virtualenv setup again and have issues, feel free to reopen!

**Comment by marcoac** [comment]
Still the same problem even in virtual environment (working on marco_pymc3 env). Is there any one workaround?
##############
Sys Info:
(marco_pymc3) mcoutinho@kleinrock:~/anaconda3/envs/marco_pymc3$ conda list | grep tqdm
tqdm                      4.29.1                   pypi_0    pypi
(marco_pymc3) mcoutinho@kleinrock:~/anaconda3/envs/marco_pymc3$ conda list | grep pandas
pandas                    0.24.0                   pypi_0    pypi
(marco_pymc3) mcoutinho@kleinrock:~/anaconda3/envs/marco_pymc3$ conda env list
# conda environments:
#
base                     /home/mcoutinho/anaconda3
marco_pymc3           *  /home/mcoutinho/anaconda3/envs/marco_pymc3
