### ISSUE TITLE
Not able to import snorkel modules:  ModuleNotFoundError: No module named 'snorkel.classification' for line :from snorkel.classification.data import DictDataset, DictDataLoader

### ISSUE THREAD

**Issue by guri1993** [snorkel-team/snorkel-tutorials#146]

**Comment by henryre** [comment]
Hi @guri1993, can you please use our Bug Report Issue template and add in some exception tracebacks? Unfortunately I'm not able to diagnose your issue without additional information.

**Comment by guri1993** [comment]
hey, that issue ot resolved but i just want to check if we can run this code on windows ?
as this is missing .bat file and the .sh file can only be run on ubuntu ,so hows it ?
I am currently trying to execute this on windows.

**Comment by henryre** [comment]
Hi @guri1993, per our README, we recommend that Windows users either use our Docker setup or the Linux subsystem: https://github.com/snorkel-team/snorkel-tutorials#getting-started. Again, I can't diagnose the above install issue without additional information.

**Comment by Shikhar-S** [comment]
Facing similar issue, I am running this on wsl. Did conda install snorkel and git clone https://github.com/snorkel-team/snorkel-tutorials.git , Then I ran 01_spam_tutorial. Here is the trace: 
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-411dfebaee6d> in <module>
----> 1 from utils import load_spam_dataset
      2 
      3 df_train, df_test = load_spam_dataset()
      4 
      5 # We pull out the label vectors for ease of use later

/mnt/c/Users/capta/Desktop/snorkel_test/snorkel-tutorials/spam/utils.py in <module>
     11 from sklearn.model_selection import train_test_split
     12 
---> 13 from snorkel.classification.data import DictDataset, DictDataLoader
     14 
     15 

ModuleNotFoundError: No module named 'snorkel.classification'
`
