### ISSUE TITLE
11 LFs in Spouse dataset?

### ISSUE THREAD

**Issue by awasthiabhijeet** [snorkel-team/snorkel-tutorials#147]
## Issue description
Table 2 in [This paper](https://arxiv.org/pdf/1711.10160.pdf) says 11 LFs were used for the spouses dataset. In spouses tutorial only 9 labelling functions are available.  

Where can the remaining 2 LFs be found?

**Comment by brahmaneya** [comment]
Hi @awasthiabhijeet, we have refactored our original set of 11 LFs (e.g. combining two LFs into one) to get the 9 LFs in the spouse tutorial.

**Comment by awasthiabhijeet** [comment]
Thanks!
The same paper shows discriminator F1 to be 54.2 but at the very end of the [spouses demo](https://github.com/snorkel-team/snorkel-tutorials/blob/master/spouse/spouse_demo.ipynb), F1 score obtained is 28.63. Why is this difference? 
I initially thought this might be due to any difference in labeling functions.

**Comment by brahmaneya** [comment]
Hi @awasthiabhijeet, the lower F1 was because we were using a simpler model (not the biLSTM mentioned in the paper). We have an upcoming fix for this (https://github.com/snorkel-team/snorkel-tutorials/pull/150).
