### ISSUE TITLE
bug in getting_started/download_data.sh

### ISSUE THREAD

**Issue by mtournier-apixio** [snorkel-team/snorkel-tutorials#148]
## Issue description

I discovered a problem when running the `getting_started.ipynb` notebook, when downloading `df_train`

## Code example/repro steps

If you are on a Mac without `wget` installed, the code in line 25 of the script `getting_started/download_data.sh` will fail.

## Suggestion for correction

exchange the statement in line 25 of the script `getting_started/download_data.sh` to `curl $DATA_URL > data.zip`

**Comment by brahmaneya** [comment]
That's a good idea @mtournier-apixio, thanks! Feel free to open a PR for this.

**Comment by mtournier-apixio** [comment]
Done! Waiting for approval 😄

**Comment by brahmaneya** [comment]
Approved, thanks @mtournier-apixio!
