### ISSUE TITLE
 https://www.dropbox.com/s/94d2wsrrwh1ioyd/weather-non-agg-DFE.csv 

### ISSUE THREAD

**Issue by anjubaoGDUT** [snorkel-team/snorkel-tutorials#151]

**Comment by anjubaoGDUT** [comment]
I can not download the dataset  weather-non-agg-DFE.csv

**Comment by brahmaneya** [comment]
Can you provide more details? What happens when you run
wget https://www.dropbox.com/s/94d2wsrrwh1ioyd/weather-non-agg-DFE.csv on your machine?

**Comment by anjubaoGDUT** [comment]
> Can you provide more details? What happens when you run
> wget https://www.dropbox.com/s/94d2wsrrwh1ioyd/weather-non-agg-DFE.csv on your machine?

 I am in China, I can not open the download link. can you provide other ways to download data sets?

**Comment by vincentschen** [comment]
Hi @anjubaoGDUT — would it help to host this dataset on GoogleDrive?

**Comment by eaubin** [comment]
FWIW, Dropbox (and other services like google drive) are also blocked by my employers proxy.
