### ISSUE TITLE
categorical classification in Snorkel 0.9

### ISSUE THREAD

**Issue by sofean-mso** [snorkel-team/snorkel-tutorials#153]
Hi,
I have installed Snorkel 0.9 and I tried to run some tutorials but I found some packages are missing such as "from snorkel.models import candidate_subclass". 
https://github.com/snorkel-team/snorkel-extraction/blob/master/tutorials/advanced/Categorical_Classes.ipynb
I may had something wrong in my installation. I actually use the following command for the installation:
conda install snorkel==0.9.0 -c conda-forge

any clarifications? 

Thanks!

**Comment by brahmaneya** [comment]
Hi @sofean-mso, this repo (Snorkel Tutorials) uses Snorkel 0.9. But the tutorial you are trying is in the Snorkel Extraction repo, which does not use the latest v0.9 Snorkel. You'll need to install Snorkel **v0.7**, which can be safely done by calling pip uninstall snorkel; pip install . from the root directory of the Snorkel Extraction repo.

**Comment by sofean-mso** [comment]
Hi @brahmaneya 
thanks for the clarification. 
Can you share any avialble example of multi-class classifction by using Snorkel 0.9? or it doesn't support that?

**Comment by brahmaneya** [comment]
You can check out the Visual Relation [tutorial](https://github.com/snorkel-team/snorkel-tutorials/blob/master/visual_relation/visual_relation_tutorial.ipynb), which has three way classification.

**Comment by sofean-mso** [comment]
thanks. Do you know what is the approach that is used there when different LFs assign a single point( like a document) into different labels? "in case of multiclass problem"

**Comment by brahmaneya** [comment]
The existing LabelModel can already handle the case where LFs give conflicting labels in a multiclass problem.
