### ISSUE TITLE
Getting Started - tutorial download

### ISSUE THREAD

**Issue by sillystring13** [snorkel-team/snorkel-tutorials#154]
## Is your feature request related to a problem? Please describe.
The getting started web page (https://www.snorkel.org/get-started/) has the user install snorkel and moves directly on to code.  It does not tell the user to git clone the tutorials repo.  This matters because the code instructions depend on extra files (utils.py) from the repo. 

## Describe the solution you'd like
Add a git clone instruction after pip install

## Describe alternatives you've considered
I found repos for snorkel docs and tutorials, but didn't see a place where I could do a pull request against the web page tutorial 

## Additional context
If users are typing along with the example they will encounter an error on the first example code chunk.  Not a big deal to download the tutorials repo, just a hiccup in the workflow. 

#
Thanks for the latest version - it looks beautiful.

**Comment by vincentschen** [comment]
Hi @sillystring13 — thanks for trying out Snorkel and pointing this out! 

We intended for the "Getting Started" page to be a text-only walkthrough of the code, to highlight, at a very high-level, the operations that Snorkel supports. A version of this is runnable in the [Tutorials repo](https://github.com/snorkel-team/snorkel-tutorials/blob/master/getting_started/getting_started.ipynb).

We'll add a "View on Github" button to make this more clear!

**Comment by sillystring13** [comment]
Thanks!  I like that solution :)

**Comment by vincentschen** [comment]
This should be reflected on https://www.snorkel.org/get-started/ — thanks again @sillystring13 for the suggestion!
