### ISSUE TITLE
Snorkel + Snorkel-Tutorial version mismatches

### ISSUE THREAD

**Issue by madisonmay** [snorkel-team/snorkel-tutorials#155]
## Issue description

Working through the snorkel-tutorials repository while using the most recent development branch of snorkel it's clear that some recent API changes in snorkel have broken the tutorial code (things like `SlicingClassifier` --> `SliceAwareClassifier`).  What is the intended behavior here?  Does the snorkel-tutorials repo track the most recent PyPI release of the snorkel package?   Most recent minor-point version release?  

Maybe it makes sense to find some way to tie snorkel-tutorial versions to snorkel versions (via github releases / explicit versioning or similar)?

**Comment by henryre** [comment]
Hi @madisonmay, thanks for trying out the tutorials and bringing this up! Our de facto SLA is to be caught up to the minor version and specify the Snorkel version in https://github.com/snorkel-team/snorkel-tutorials/blob/master/requirements.txt. Here, we had a weird case where a patch version wasn't fully backwards compatible. We should definitely make the Snorkel version more visible, and can make the update for this patch. I haven't seen many tutorial repos use releases/explicit versioning themselves, but let me know if you have examples!

**Comment by madisonmay** [comment]
Hi @henryre -- thanks for the quick follow-up.  I honestly hadn't noticed the requirements.txt (or the Dockerfile) but that policy makes perfect sense.  

I did a quick look around the internet at spacy / pytorch / tensorflow tutorials and I doesn't seem like releases / explicit versioning is common -- most of those didn't even specify versions in requirements.txt, so looks like that's a strict improvement over the baseline haha.  

Thanks for pointing me to the right version to run.  If I have some time this evening I can try to update the imports to 0.9.2 for when that minor point release is ready for prime time.

**Comment by henryre** [comment]
@madisonmay sounds great! Happy to help out there as well.
