### ISSUE TITLE
spam/utils func get_keras_early_stopping doesn't use parameter "patience"

### ISSUE THREAD

**Issue by sillystring13** [snorkel-team/snorkel-tutorials#157]
## Issue description
https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/utils.py#L88
Function get_keras_early_stopping references hard value of 10 in the function instead of the parameterized "patience"

## Code example/repro steps

The issue does not create a bug in any example tutorials as given, but wouldn't use any updated user values in the spam tutorial

**Comment by vincentschen** [comment]
Hi @sillystring13 — you're right, thanks for the catch! You're welcome to open a PR for a fix! Otherwise, we'll address this shortly!

**Comment by sillystring13** [comment]
I'll work on the PR today :)

Would y'all mind if I parameterize the monitor as well?  That way folks can stop on whichever max they are looking for, such as the training accuracy or an F1 score.
