### ISSUE TITLE
spam tests do not pass

### ISSUE THREAD

**Issue by cyrilou242** [snorkel-team/snorkel-tutorials#160]
## Issue description
Tests for spam tutorial do not succeed with original source code.

## Code example/repro steps
Without any change to the source code. 
`tox -e spam -- sync` raises an error from `spam/01_spam_tutorial.py`:

```python
df_fp_dev.sample(5, random_state=3)
```
```python


ValueError                                Traceback (most recent call last)
<ipython-input-44-2014b6aeafd7> in <module>
      6 df_fp_dev["probability"] = probs_dev[buckets[(SPAM, HAM)], 1]
      7 
----> 8 df_fp_dev.sample(5, random_state=3)
~/build/snorkel-team/snorkel-tutorials/.tox/spam/lib/python3.6/site-packages/pandas/core/generic.py in sample(self, n, frac, replace, weights, random_state, axis)
   4863                              "provide positive value.")
   4864 
-> 4865         locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
   4866         return self.take(locs, axis=axis, is_copy=False)
   4867 
mtrand.pyx in mtrand.RandomState.choice()
ValueError: Cannot take a larger sample than population when 'replace=False'
```

This error was also raised in a Travis CI here:
https://travis-ci.com/snorkel-team/snorkel-tutorials/jobs/241146646

## Expected behavior
Tests should pass.

## System info
Snorkel installation: pip
* Build command I used:
```
python3 -m pip install -U 'tox>=3.13.0,<4.0.0'
python3 -m pip install -r requirements.txt
python3 -m pip install -r spam/requirements.txt  # Change based on tutorial.
```
* OS:  
```
System Version: macOS 10.13.6 (17G3025)
Kernel Version: Darwin 17.7.0
```
* Python version: `Python 3.6.6`
* Snorkel version: `snorkel==0.9.0`

## Additional context
The following is the dataframe from which we try to sample 5 values. 
There are only 4 values in this dataframe.

```
                                    text      label      probability
313                     Aslamu Lykum... From Pakistan﻿   1   0.0
431             CHECK OUT Eminem - Rap God LYRIC VIDEO   1   0.0
189          /watch?v=aImbWbfQbzg watch and subscrible   1   0.0
334  Check out Em&#39;s dope new song monster here:...   1   0.0
```

This is a dataframe of false positive, so it is ok not to have too much of them.
I could not find why there could be 5 (or more) before but only 4 now. I think it may be due to an optimization made in Snorkel, a subtle change in a dependency or some random states magic. (definitely not sure)

A simple solution: replace 
`let's take a look at 5 random false negatives` by `let's take a look at 4 random false negatives` and only sample `4` false negatives.

**Comment by cyrilou242** [comment]
I could put some thoughts in this. 

Spacy released a new version 2 days ago: https://github.com/explosion/spaCy/releases/tag/v2.2.0
--> The bug happens for this version (and higher)

With `spacy>=2.1.6,<2.2.0` in the spam `requirements.txt` instead of `spacy>=2.1.6`, tests pass :)

2 possible solutions: 
- _option 1_:  fix the version of spacy as above
- _option 2_: change the tutorial to only display 4 false negatives.  

_option 1_ will ensure that the tutorial will not be impacted by newer version of spacy. (not sure if it is totally true though, because there is still that `python -m spacy download en_core_web_sm` line)  
_option 2_ takes into account spacy improvements, (and they are beneficial to snorkel performance so that's cool), but the tutorial and spacy will have a stronger coupling

**Comment by vincentschen** [comment]
Thanks for digging in here @cyrilou242!

Pinning the version seems like a reasonable fix to me so that we have a stable tutorial — you're welcome to open a PR for this fix!

**Comment by vincentschen** [comment]
Just merged a fix! Thanks for surfacing this @cyrilou242
