### ISSUE TITLE
Unclear Text

### ISSUE THREAD

**Issue by eggie5** [snorkel-team/snorkel-tutorials#166]
The text says "Let’s generate a set of probabilistic labels for that training set" however, the code goes on to use the wrong API which generates discriminative labels:

```
preds_train = label_model.predict(L_train)
``` 

https://github.com/snorkel-team/snorkel-tutorials/blob/master/crowdsourcing/crowdsourcing_tutorial.ipynb?short_path=451bc07#L992

Also here

https://www.snorkel.org/use-cases/crowdsourcing-tutorial#use-soft-labels-to-train-end-model

**Comment by brahmaneya** [comment]
Hi Alex,

We'll fix the text, thanks for the catch!

**Comment by vincentschen** [comment]
Looks like @brahmaneya addressed this!
