### ISSUE TITLE
ON installation issues importing modules

### ISSUE THREAD

**Issue by MrRobot2211** [snorkel-team/snorkel-tutorials#170]
## Issue description
I tried installing snorkel both with conda and pip , in both cases it failed importing modules

## Code example/repro steps

from snorkel.augmentation import transformation_function

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-93ad1079fd64> in <module>
     10 from nltk.corpus import wordnet as wn
     11 
---> 12 from snorkel.augmentation import transformation_function
     13 
     14 nltk.download("wordnet", quiet=True)

~/anaconda3/lib/python3.7/site-packages/snorkel/augmentation/__init__.py in <module>
      1 """Programmatic data set augmentation: TF creation and data generation utilities."""
      2 
----> 3 from .apply.core import TFApplier  # noqa: F401
      4 from .apply.pandas import PandasTFApplier  # noqa: F401
      5 from .policy.core import ApplyAllPolicy, ApplyEachPolicy, ApplyOnePolicy  # noqa: F401

~/anaconda3/lib/python3.7/site-packages/snorkel/augmentation/apply/core.py in <module>
      6 from snorkel.augmentation.tf import BaseTransformationFunction
      7 from snorkel.types import DataPoint, DataPoints
----> 8 from snorkel.utils.data_operators import check_unique_names
      9 
     10 

ModuleNotFoundError: No module named 'snorkel.utils.data_operators'; 'snorkel.utils' is not a package

## Expected behavior
should import
## Screenshots
No screenshots of code!

## System info

* How you installed Snorkel (conda, pip, source):
-conda 
-pip
* Build command you used (if compiling from source):
* OS:Ubuntu 18
* Python version:python 3
* Snorkel version:0.9.2
* Versions of any other relevant libraries:

## Additional context
+

**Comment by vincentschen** [comment]
Hi @MrRobot2211 — sorry about that! What was the exact set of commands you ran to install? I'll try to reproduce it on my end.

Also, if this is related to the [core project](https://github.com/snorkel-team/snorkel) as opposed to this tutorials repo, feel free to open an issue in the main repo!
