### ISSUE TITLE
Padding with space in get_feature_arrays() in spouse tutorial

### ISSUE THREAD

**Issue by phosseini** [snorkel-team/snorkel-tutorials#172]
## Issue description

In padding cases, there will be an issue in concatenating list and string (since these two cannot be concatenated.)

## Code example/repro steps

Current method:

```
def pad_or_truncate(l, max_length=40):
        return l[:max_length] + [""] * (max_length - len(l))
```

Changing the method to for example a method like the following will solve the problem:

```
def pad_or_truncate(l, max_length=40):
        return l[:max_length] + " ".join([""] * (max_length - len(l) + 1))
```

**Comment by vincentschen** [comment]
Thanks for surfacing this @phosseini — can you share an example test case that breaks this?

Then, happy to accept any fixes with a PR!

**Comment by phosseini** [comment]
This is an example (as far as I know the inputs are lists of tokens?)

<img width="649" alt="Screen Shot 2019-11-18 at 3 25 20 PM" src="https://user-images.githubusercontent.com/25105263/69091233-dd353a00-0a17-11ea-8d58-3dd258c9116d.png">

One solution to resolve the issue could be updating the `pad_or_truncate()` like the following:

```
def pad_or_truncate(l, max_length=10):
    return l[:max_length] + " ".join([""] * (max_length - len(l) + 1))
```

If it sounds right to you, I'll submit a PR.

**Comment by vincentschen** [comment]
It looks like `pad_or_truncate` accepts lists, but you're calling `map(pad_or_truncate, left)`, which maps each element (which is a `str`) to function arg, `l`.

In our [code](https://github.com/snorkel-team/snorkel-tutorials/blob/master/spouse/tf_model.py#L19-L21), we're actually passing a _list of lists_ into the `map` — the outer list contains all examples, and the inner list contains tokens for an example.

To modify your code, removing the `map` should fix things!
