### ISSUE TITLE
Weather Dataset Link Broken [non-agg File]

### ISSUE THREAD

**Issue by anassalamah** [snorkel-team/snorkel-tutorials#182]
## Issue description

It seems that the link to download the weather dataset for the non-aggregate file is broken

## Code example/repro steps

I can't get the file using wget nor can I get it using the link itself

## Expected behavior
should download the file

**Comment by paroma** [comment]
Wasn't able to reproduce this issue. Ran the following commands independently to check:

```
wget https://www.dropbox.com/s/94d2wsrrwh1ioyd/weather-non-agg-DFE.csv -P data
wget https://d1p17r2m4rzlbo.cloudfront.net/wp-content/uploads/2016/03/weather-evaluated-agg-DFE.csv -P data
```

**Comment by anassalamah** [comment]
problem on my side
