### ISSUE TITLE
pip install clash with sckit-learn

### ISSUE THREAD

**Issue by johncalab** [snorkel-team/snorkel-tutorials#214]
I created a fresh virtual environment using python 3.8, and when I tried to pip install snorkel it threw an error upon installing scikit-learn (`It seems that scikit-learn cannot be built with OpenMP support.`). Installing from 3.6 worked. Is the incompatibility expected?

**Comment by brahmaneya** [comment]
Hi @johncalab, snorkel is currently only compatible with python 3.6 and 3.7. Can you try switching to one of those versions?

**Comment by johncalab** [comment]
@brahmaneya Thanks for the quick reply. Yes, switching to 3.6 is fine and snorkel seems to have installed without any problems. What changed in 3.8 that causes an incompatibility?
Also (unrelated), is flying squid meant to eventually replace snorkel?
