### ISSUE TITLE
Update tutorials to a newer version of Snorkel package

### ISSUE THREAD

**Issue by levchikm** [snorkel-team/snorkel-tutorials#215]
You have recently updated a snorkel package. There are breaking changes in version v0.9.4. Now MajorityLabelVoter, LabelModel imports from snorkel.labeling.mode. 

It would be nice if you update tutorials. Now the getting started tutorial from https://www.snorkel.org/get-started/ is not working with the current version of package.

**Comment by vincentschen** [comment]
Thanks for the note — we'll push an upgrade this weekend!
