### ISSUE TITLE
CalledProcessError: Command '['bash', 'download_data.sh']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by zahrakolagar** [snorkel-team/snorkel-tutorials#220]
hi,
thank you very much for your tutorials. I wanted to try out your spam tutorial number two using the docker image you have provided, but as soon as I run the cell for loading the data I run to the following error:
CalledProcessError: Command '['bash', 'download_data.sh']' returned non-zero exit status 2.

the URL for the data seems to be okay, so I cannot really say what the problem is here. I copied a full traceback here:
: invalid option namee 2: set: pipefail

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-4-12e992e90ddd> in <module>
      1 from utils import load_spam_dataset
      2 
----> 3 df_train, df_test = load_spam_dataset(load_train_labels=True)
      4 
      5 # We pull out the label vectors for ease of use later

/app/spam/utils.py in load_spam_dataset(load_train_labels, split_dev_valid)
     21     except subprocess.CalledProcessError as e:
     22         print(e.stderr.decode())
---> 23         raise e
     24     filenames = sorted(glob.glob("data/Youtube*.csv"))
     25 

/app/spam/utils.py in load_spam_dataset(load_train_labels, split_dev_valid)
     18         os.chdir("spam")
     19     try:
---> 20         subprocess.run(["bash", "download_data.sh"], check=True, stderr=subprocess.PIPE)
     21     except subprocess.CalledProcessError as e:
     22         print(e.stderr.decode())

/usr/local/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    436         if check and retcode:
    437             raise CalledProcessError(retcode, process.args,
--> 438                                      output=stdout, stderr=stderr)
    439     return CompletedProcess(process.args, retcode, stdout, stderr)
    440 

CalledProcessError: Command '['bash', 'download_data.sh']' returned non-zero exit status 2.

I would be grateful if you could help. Thank you in adavnce

**Comment by Carmenvanveen** [comment]
I have the same issue.

**Comment by raj5287** [comment]
@Carmenvanveen I am getting the same error on win 10, can you please tell me what you did?

**Comment by Carmenvanveen** [comment]
@raj5287 was not able to solve it unfortunately.

**Comment by raj5287** [comment]
@Carmenvanveen okay, I am able to run now.

**Comment by Carmenvanveen** [comment]
@raj5287 how did you solve it (even with running with Docker I have the same problem)?

**Comment by raj5287** [comment]
@Carmenvanveen downloaded the datasets from the links given in the download-data.sh, place it in the data folder in the same directory and then changed the codes in the tutorial notebook from data.py to load the data in the notebook

**Comment by rileynjohnson** [comment]
download the data from http://archive.ics.uci.edu/ml/machine-learning-databases/00380/YouTube-Spam-Collection-v1.zip and put them in a spam\data folder.

Then comment out these lines in utils.py:
   #if os.path.basename(os.getcwd()) == "snorkel-tutorials":
    #    os.chdir("spam")
   # try:
    #    subprocess.run(["bash", "download_data.sh"], check=True, stderr=subprocess.PIPE)
   # except subprocess.CalledProcessError as e:
   #     print(e.stderr.decode())
   #     raise e
   
   Then restart your jupyter kernel (to clear the old version of utils.py) and re-run.  Should work nicely.

**Comment by abs007** [comment]
@rileynjohnson I was trying out the spouse tutorial but got the same Error. Plus, I tried changing the code in the utils.py file under the spouse folder like how you mentioned but saw that it's already written there. I'd really appreciate your help.
