### ISSUE TITLE
Visual Relation Tutorial - Error with last step trainer.fit(...)

### ISSUE THREAD

**Issue by weehyong** [snorkel-team/snorkel-tutorials#223]
## Issue description
Error at last step of visual_relation_tutorial notebook.
https://github.com/snorkel-team/snorkel-tutorials/blob/master/visual_relation/visual_relation_tutorial.ipynb

## Code example/repro steps
from snorkel.classification import Trainer

trainer = Trainer(
    n_epochs=1,  # increase for improved performance
    lr=1e-3,
    checkpointing=True,
    checkpointer_config={"checkpoint_dir": "checkpoint"},
)
trainer.fit(model, [dl_train])

Stack Trace
--------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/snorkel/classification/multitask_classifier.py in forward(self, X_dict, task_names)
    215                             output = self.module_pool[operation.module_name].forward(
--> 216                                 *inputs
    217                             )

~/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    155         outputs = self.parallel_apply(replicas, inputs, kwargs)
--> 156         return self.gather(outputs, self.output_device)
    157 

~/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in gather(self, outputs, output_device)
    167     def gather(self, outputs, output_device):
--> 168         return gather(outputs, output_device, dim=self.dim)
    169 

~/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py in gather(outputs, target_device, dim)
     67     try:
---> 68         res = gather_map(outputs)
     69     finally:

~/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py in gather_map(outputs)
     54         if isinstance(out, torch.Tensor):
---> 55             return Gather.apply(target_device, dim, *outputs)
     56         if out is None:

~/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py in forward(ctx, target_device, dim, *inputs)
     53     def forward(ctx, target_device, dim, *inputs):
---> 54         assert all(map(lambda i: i.is_cuda, inputs))
     55         target_device = _get_device_index(target_device, True)

AssertionError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
 in 
      7     checkpointer_config={"checkpoint_dir": "checkpoint"},
      8 )
----> 9 trainer.fit(model, [dl_train])

~/.local/lib/python3.6/site-packages/snorkel/classification/training/trainer.py in fit(self, model, dataloaders)
    202 
    203                 # Perform forward pass and calcualte the loss and count
--> 204                 loss_dict, count_dict = model.calculate_loss(X_dict, Y_dict)
    205 
    206                 # Update running loss and count

~/.local/lib/python3.6/site-packages/snorkel/classification/multitask_classifier.py in calculate_loss(self, X_dict, Y_dict)
    249 
    250         labels_to_tasks = self._get_labels_to_tasks(Y_dict.keys())
--> 251         outputs = self.forward(X_dict, task_names=labels_to_tasks.values())
    252 
    253         # Calculate loss for each task

~/.local/lib/python3.6/site-packages/snorkel/classification/multitask_classifier.py in forward(self, X_dict, task_names)
    222                             )
    223                     except Exception:
--> 224                         raise ValueError(f"Unsuccessful operation {operation}.")
    225                     outputs[operation.name] = output
    226 

ValueError: Unsuccessful operation Operation(name=word_emb_op, module_name=word_emb, inputs=[('_input_', 'sub_category'), ('_input_', 'obj_category')]).

## Expected behavior
trainer.fit() should complete execution

## System info
* How you installed Snorkel (conda, pip, source):
pip install

* Build command you used (if compiling from source):
* OS:
Linux (ubuntu 18.04)

* Python version:
Python 3.6

* Snorkel version:
* Versions of any other relevant libraries:

## Additional context
Was trying to run through the tutorial to reproduce the work.

**Comment by weehyong** [comment]
@vincentschen Not sure whether you have seen this issue before?

**Comment by weehyong** [comment]
I removed word_emb_op in model.py and updated the FC layer
And re-run the code and have the same micro_f1 score as the tutorial
{'visual_relation_task/valid_dataset/valid/f1_micro': 0.34615384615384615}

Changes made - 

 # define an operation to concatenate image features and word embeddings
def get_op_sequence():
    # define feature extractors for each of the (union, subject, and object) image crops
    union_feat_op = Operation(
        name="union_feat_op",
        module_name="feat_extractor",
        inputs=[("_input_", "union_crop")],
    )

    sub_feat_op = Operation(
        name="sub_feat_op",
        module_name="feat_extractor",
        inputs=[("_input_", "sub_crop")],
    )

    obj_feat_op = Operation(
        name="obj_feat_op",
        module_name="feat_extractor",
        inputs=[("_input_", "obj_crop")],
    )

    # define an operation to extract word embeddings for subject and object categories
    word_emb_op = Operation(
        name="word_emb_op",
        module_name="word_emb",
        inputs=[("_input_", "sub_category"), ("_input_", "obj_category")],
    )

    # define an operation to concatenate image features and word embeddings
    concat_op = Operation(
        name="concat_op",
        module_name="feat_concat",
        **inputs=["obj_feat_op", "sub_feat_op", "union_feat_op"],**
    )

    # define an operation to make a prediction over all concatenated features
    prediction_op = Operation(
        name="head_op", module_name="prediction_head", inputs=["concat_op"]
    )

    **return [
        sub_feat_op,
        obj_feat_op,
        union_feat_op,
        concat_op,
        prediction_op,
    ]**

And in create_model, 
    fc = nn.Linear(in_features * 3, 3)

**Comment by vincentschen** [comment]
Hi @weehyong, thanks for posting an issue!

Would you mind sharing some metadata to help me better understand your configuration?

First, what version of Snorkel do you have installed?
```python
>> import snorkel; print(snorkel.__version__)
0.9.5
```

Second, what does the `data/glove` directory look like? It should have a file containing the downloaded glove embeddings.
```
# pwd
/app/visual_relation
# ls data/glove
glove.6B.100d.txt
```

**Comment by weehyong** [comment]
@vincentschen  

Verified that the Snorkel version is **0.9.5**
Also verified that I see glove.6B.100d.txt in data/glove.
I was able to load the glove embedding file successfully too.

**Comment by vincentschen** [comment]
Thanks for checking @weehyong!

Looking at the errors, the assertion error on `assert all(map(lambda i: i.is_cuda, inputs))` leads me to believe that we're not properly moving the embeddings to the GPU.

Does the tutorial work properly on a CPU machine?

**Comment by weehyong** [comment]
I tried it on a single-GPU machine (K80) and was able to complete the tutorial.

The earlier errors was coming from running it on a machine with 2 GPUs (K80s).
Thank you @vincentschen for the suggestions.

Closing out the issue.
