### ISSUE TITLE
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above - 01_spam_tutorial

### ISSUE THREAD

**Issue by olijnykn** [snorkel-team/snorkel-tutorials#225]
**Issue**
An import error occurs when I execute the 4th cell in the 01_spam_tutorial notebook. Cell code lines executed:
`from utils import load_spam_dataset`
`df_train, df_test = load_spam_dataset()`
`Y_test = df_test.label.values`

**Error Message**
ImportError                               Traceback (most recent call last)
<ipython-input-3-411dfebaee6d> in <module>
----> 1 from utils import load_spam_dataset
      2 
      3 df_train, df_test = load_spam_dataset()
      4 
      5 # We pull out the label vectors for ease of use later

/app/spam/utils.py in <module>
     11 from sklearn.model_selection import train_test_split
     12 
---> 13 from snorkel.classification.data import DictDataset, DictDataLoader
     14 
     15 

/usr/local/lib/python3.6/site-packages/snorkel/classification/__init__.py in <module>
      5 from .multitask_classifier import MultitaskClassifier  # noqa: F401
      6 from .task import Operation, Task  # noqa: F401
----> 7 from .training.loggers import (  # noqa: F401
      8     Checkpointer,
      9     CheckpointerConfig,

/usr/local/lib/python3.6/site-packages/snorkel/classification/training/loggers/__init__.py in <module>
      2 from .log_manager import LogManager, LogManagerConfig  # noqa: F401
      3 from .log_writer import LogWriter, LogWriterConfig  # noqa: F401
----> 4 from .tensorboard_writer import TensorBoardWriter  # noqa: F401

/usr/local/lib/python3.6/site-packages/snorkel/classification/training/loggers/tensorboard_writer.py in <module>
      1 from typing import Any
      2 
----> 3 from torch.utils.tensorboard import SummaryWriter
      4 
      5 from snorkel.types import Config

/usr/local/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py in <module>
      2 from distutils.version import LooseVersion
      3 if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
----> 4     raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
      5 del LooseVersion
      6 del tensorboard

ImportError: TensorBoard logging requires TensorBoard version 1.15 or above

**System Information**
Used the Docker setup recommendation provided by the Getting Started instructions: https://github.com/snorkel-team/snorkel-tutorials (python3 scripts/docker_launch.py spam --build)
Using Ubuntu 

**Additional Info**
I found a fix a week ago, but I can't seem to replicate it.

**Comment by henryre** [comment]
Hi @olijnykn, thanks for reporting! Can you run `pip freeze` from inside the container (can run `! pip freeze` in a notebook cell) and let us know the output? This may be because we're pulling requirements from `snorkel/master`.

**Comment by Lin-Leon-MENG** [comment]
Hi @henryre, I also had this issue when I was running those `load_spam_dataset()` cells, somehow rerunning the cell would fix it.

But when I was working on the "03_spam_data_slicing_tutorial" notebook, the following cell would give the same ImportError, resulted from the `import slicing_function` line. And rerunning the code won't help here.

```
import re
from snorkel.slicing import slicing_function


@slicing_function()
def short_comment(x):
    """Ham comments are often short, such as 'cool video!'"""
    return len(x.text.split()) < 5


sfs = [short_comment]
```

FYI, this is part of the output when I run `! pip freeze` inside the container. I guess updating the Dockerfile would fix that? Thanks!

```
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
```

**Comment by caticoa3** [comment]
Ran into this issue as well. 
Updating tensor-board to 2.3.0 resolved the issue for me. 
I test the modification from within the docker container. 
Then modified the snorkel-requriements.txt in the Dockerfile, rebuilt the container, and ran the spam tutorial notebook. 
The change is hacky but I think it's safer than modifying the snorkel [requriemnents]('https://github.com/snorkel-team/snorkel/blob/master/requirements.txt').
