### ISSUE TITLE
Improper Assignment of predicted labels to dataframe - Snorkel Drybell tutorial

### ISSUE THREAD

**Issue by rbhatia46** [snorkel-team/snorkel-tutorials#226]
## Issue description

Hi,
In the snorkel drybell tutorial(**drybell/drybell_spark.py**), after using training label model to predict the probabilities, the following line is used to assign the predicted probabilities to PySpark dataframe - 
```python
y_prob_sql_array = F.array([F.lit(y) for y in y_prob])
data_labeled = data.withColumn("y_prob", y_prob_sql_array)
```
This assigns the same array of labels to every single row.(refer column **static_probability**)

<img width="504" alt="Screenshot 2020-08-12 at 2 11 11 PM" src="https://user-images.githubusercontent.com/20289101/90006451-80209900-dcb6-11ea-9641-87fd856c661f.png">

How can I make sure to assign each prediction probability gets assigned to only the specific row.
Please help me here. I know this is a Spark related doubt but any help would be appreciated.

## System info

* How you installed Snorkel (conda, pip, source): pip
* OS: MacOS Mojave 10.14.6
* Python version: 3.6
* Snorkel version: 0.9.3
* Versions of any other relevant libraries: Spark 3.0

**Comment by henryre** [comment]
Hi @rbhatia46, can you share some detail on what the values in `y_prob` are and what you'd expect to see? As an example, if you have three classes and these data points had no LF votes, then we'd expect to see probabilities like this output from the label model.
