### ISSUE TITLE
Fixing the error wherein a 'CalledProcessError' is called when trying to run the spouse_demo.ipynb file 

### ISSUE THREAD

**Issue by abs007** [snorkel-team/snorkel-tutorials#269]
![Screenshot (28)](https://user-images.githubusercontent.com/53483248/155394677-0173442c-4717-469b-9534-305c0e68bd86.png)

Trying to fix this issue.

**Comment by rsmith49** [comment]
Hi @abs007, can you provide some details about your OS (name, version, any other details)?

If you are using Windows subsystem for Linux, [this](https://askubuntu.com/questions/1044280/set-eo-pipefail-not-working-in-windows-subsystem-for-linux-ubuntu-16-04) may be relevant.

**Comment by abs007** [comment]
Hi. I'm working with the windows 10 os.

**Comment by abs007** [comment]
I also actually could work out a fix for this issue. I did this by pasting the code for reading the data from the utils.py file inside the code block
![fix - load_data()](https://user-images.githubusercontent.com/53483248/155460803-83b02665-e118-4641-a652-ac342618fd90.png)

**Comment by abs007** [comment]
@rsmith49 Is it okay if I start working on this and submit a pull request?

**Comment by rsmith49** [comment]
@abs007 glad you found a workaround for your machine!

Definitely feel free to submit a PR if you feel there is a general way to account for other people running into the same problem
