### ISSUE TITLE
Pandas version mismatch in "visual_relation" tutorial

### ISSUE THREAD

**Issue by tgrippa** [snorkel-team/snorkel-tutorials#282]
## Issue description
When using the Docker installation of "visual_relation" tutorial, the final step with training of the model fail with the following error : 'DataFrame' object has no attribute 'as_matrix'. 

After some exploration it seems that the version of Pandas in the file "snorkel-requirements.txt" downloaded with wget overwrite the version required (i.e. pandas>=0.24.0,<0.25.0 according to [visual_relation/requirements.txt](https://github.com/snorkel-team/snorkel-tutorials/blob/master/visual_relation/requirements.txt).

Downgrading manually Pandas to version 0.24.0 successfully fixed the error. 

## Code example/repro steps
`python3 scripts/docker_launch.py visual_relation --build` then select the notebook "visual_relation_tutorial.ipynb" and run it until the "Train and Evaluate Model" section. 

## Expected behavior
No issues should raise. 

## System info
* How you installed Snorkel (conda, pip, source): Docker
* OS: Ubuntu 20.04.4

## Additional context
I solved the error by downgrading Pandas using the following commands:
`docker exec -it YOUR_DOCKER_CONTAINER_ID bash`
`pip3 install pandas==0.24.0`

**Comment by abnokubi** [comment]
This problem was caused by deprecated pandas method.
It works with the following patch, using values instead of as_matrix():

```
diff --git a/visual_relation/model.py b/visual_relation/model.py
index c507d76..9333fd7 100644
--- a/visual_relation/model.py
+++ b/visual_relation/model.py
@@ -132,7 +132,7 @@ class WordEmb(nn.Module):
         )
 
     def _get_wordvec(self, word):
-        return self.word_embs.loc[word].as_matrix()
+        return self.word_embs.loc[word].values #.as_matrix()
 
     def forward(self, obj_category, sub_category):
         obj_emb = self._get_wordvec(obj_category)
```

**Comment by tgrippa** [comment]
Hi @abnokubi and thank you for your solution. Could you make a proper pull request with the modification so that everybody can have a fixed version available on the repo ? 

Best
